apiVersion: apps/v1
kind: Deployment
metadata:
  name: hilyx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hilyx
  template:
    metadata:
      labels:
        app: hilyx
    spec:
      containers:
      - name: hilyx
        image: douillard/hilyx:v1
        ports:
        - containerPort: 3000

